name: KICPA Job Watcher

on:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 실행
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run watcher
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          mkdir -p .state
          python kicpa_job_watcher.py
